[package]
name = "raydium-contract-instructions"
version = "0.1.0"
edition = "2024"


[dependencies]
spl-token = { version = "8.0.0", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "6.0.0", features = [
    "no-entrypoint",
] }
thiserror = "1.0.20"
ahash = "=0.8.11"
solana-program = "=2.2.1"
